server:
  port: 8008

spring:
  application:
    name: owner_service
  datasource:
    url: jdbc:h2:mem:owner
#    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/ad_2020ffc791f1c2c?user=b2e5f907de0ef6&password=c926be73
#    username: root
#    password: root1234
    schema: classpath*:hsqldb/schema.sql
    data: classpath*:hsqldb/data.sql
   # initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: update
#      ddl-auto: create
      show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console