server:
  port: 8008

spring:
  application:
    name: owner_service
  datasource:
#    url: jdbc:h2:mem:owner
#    schema: classpath*:hsqldb/schema.sql
#    data: classpath*:hsqldb/data.sql

#    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_d44226ab36e5046?user=b560f59049d755&password=bc74479f
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
# ddl-auto=none and mode = always results in execution of schema.sql
# mode always results in execution of data.sql
    initialization-mode: always
#    username: root
#    password: root1234

  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: update
#      ddl-auto: create
      show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console